FROM golang:1.26-alpine

RUN apk add --no-cache wget && \
    go install github.com/air-verse/air@v1.61.7

WORKDIR /workspace

COPY go.mod go.sum ./

RUN go mod download

ENV PATH=/go/bin:$PATH

CMD ["air", "-c", "services/market-state-api/.air.toml"]
